const data = {
    products: [
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'FitShirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 70,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Golf Pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 79,
            brand: 'Oliver',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Smart Looking Pants',
        },
        {
            name: 'Classic Pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 85,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pants',
        },
        {
            name: 'Classic Pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 100,
            brand: 'Uniqlo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pants',
        },
        
    ],
};

export default data;